language: perl
perl:
  # - "5.22"
  # - "5.20"
  # - "5.18"
  # - "5.16"
  # - "5.14"
  - "5.12"

before_install:
    - sudo apt-get update -q
    - sudo apt-get install -y libgmp-dev
    - cpanm Test::Pod # optional dependency

install:
    - cpanm -v --installdeps --notest .

script: "perl sonde-parser.pl --file=example.sounding"

notifications:
  recipients:
    - adamabernathy@gmail.com
  email:
    on_success: change
    on_failure: always
