language: perl
perl:
  - "5.10"
  - "5.12"
  - "5.14"

script: "perl -c sonde-parser.pl --file=example.sounding"

notifications:
  recipients:
    - adamabernathy@gmail.com
  email:
    on_success: change
    on_failure: always
